### ISSUE TITLE
Few issues during setup

### ISSUE THREAD

**Issue by amin-nas** [sketch-pm/skpm#11]
Disclaimer: aint so good at this coding thing :)
I got a few errors while testing this. Not sure if I'm following the steps as intended. Here's what I did:

1. Created a new folder pluginTest, not in the sketch plugins folder
2. Ran skpm init
3. Ran skpm build, and got this error:

> Error: ENOENT: no such file or directory, mkdir '/Users/aminnassiri/Projects/pluginTest/plugin.sketchplugin/Contents/Sketch'

4. Added the folders manually and ran skpm build again. Got this error:

> error Error while building ./my-command.js
{ SyntaxError: /Users/aminnassiri/Projects/pluginTest/src/my-command.js: Unterminated string constant (2:31)
  1 | export default function (context) {
> 2 |   context.document.showMessage('It\'s alive 🙌\')

5. Changed the string and ran skpm build again. Worked this time.
6. Installed the plugin and tested it. Works!
7. Ran the skpm link and got this error:

> Amins-MBP:pluginTest aminnassiri$ skpm link /Users/aminnassiri/Library/Application\ Support/com.bohemiancoding.sketch3/Plugins
error Error while reading the package.json file
{ Error: Cannot find module '/Users/aminnassiri/Projects/pluginTest/Users/aminnassiri/Library/Application Support/com.bohemiancoding.sketch3/Plugins/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/skpm/lib/skpm-link.js:24:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

**Comment by mathieudutour** [comment]
Thanks for the report!

> Error: ENOENT: no such file or directory, mkdir '/Users/aminnassiri/Projects/pluginTest/plugin.sketchplugin/Contents/Sketch'

I'll fix that thanks

> error Error while building ./my-command.js
{ SyntaxError: /Users/aminnassiri/Projects/pluginTest/src/my-command.js: Unterminated string constant (2:31)
1 | export default function (context) {
2 | context.document.showMessage('It's alive 🙌')

That should be fix in the version 0.4.7 (https://github.com/sketch-pm/skpm/pull/10)

> Ran the skpm link and got this error:

`skpm link` should be called with the path to your new folder (here: `/Users/aminnassiri/Projects/pluginTest`)

I could probably check that the path given is not the path to the `com.bohemiancoding.sketch3/Plugins` folder

**Comment by mathieudutour** [comment]
should be fixed in 0.4.8

Feel free to come back with any feedback and suggestions that you have, I'd love to see if it meets other use cases than mine
