### ISSUE TITLE
`logs` command

### ISSUE THREAD

**Issue by jongold** [sketch-pm/skpm#14]
Something I find myself doing _constantly_ is
`tail -f ~/Library/Logs/com.bohemiancoding.sketch3/Plugin\ Output.log`

Sometimes this file gets trashed (why?), so you have to do
`touch ~/Library/Logs/com.bohemiancoding.sketch3/Plugin\ Output.log` and then run it again.

🙃 

Do you think it's within the scope of `skpm` to add a `logs` command that wraps ^^^? Happy to write the code if you're into it.

**Comment by mathieudutour** [comment]
interesting. I was thinking of something like this but the way I'm seeing logs is by starting sketch from the terminal. I guess both approaches work.

Happy to accept either

**Comment by mathieudutour** [comment]
fixed in https://github.com/sketch-pm/skpm/commit/917e8c1ccd3d3a4a9011043e36e7691f563e9290
