### ISSUE TITLE
updating the plugin during development

### ISSUE THREAD

**Issue by amin-nas** [sketch-pm/skpm#16]
After a code change and running the build command, how would I go about updating the locally installed plugin?

I ran the link command and I can see the symlink in sketch plugin folder. Not sure what's the purpose of this command.

**Comment by mathieudutour** [comment]
Once I have `link` my plugin, I usually run `skpm build --watch` and every time I change my code, the plugin is compiled.

If you have enabled the developer mode for sketch (https://github.com/sketch-pm/skpm/issues/8), it should just work.

Does it resolve your issue or did I misunderstand?

**Comment by amin-nas** [comment]
I have the developer mode enabled, and tried `skpm build --watch`. I see the plugin being complied on every change. But when I run the plugin from Sketch's Plugin menu, I dont see the update. Wondering if I'm not following the setup instructions correctly.

Attached a screenshot of the Sketch plugins folder.
![screen shot 2017-02-20 at 7 22 31 am](https://cloud.githubusercontent.com/assets/491202/23125105/32647198-f73e-11e6-9a71-12ae646c114c.png)

**Comment by mathieudutour** [comment]
is the symlink going to the right place?

**Comment by amin-nas** [comment]
I believe so. Is the expectation that after running the `skpm link` command, the plugin is automatically installed? I assumed that's the purpose of it, but it didn't happen on my side.

<img width="1074" alt="screen shot 2017-02-20 at 7 36 11 am" src="https://cloud.githubusercontent.com/assets/491202/23125418/97dea2c2-f73f-11e6-9720-9d3650ea132f.png">

**Comment by mathieudutour** [comment]
yes i should (but there could be a bug). If you right-click -> Show information on the symlink, it should show were it's pointing to

**Comment by amin-nas** [comment]
Just started a fresh project and followed the steps. All the commands were executed successfully, but here's what I see after:
<img width="1231" alt="screen shot 2017-02-20 at 7 53 42 am" src="https://cloud.githubusercontent.com/assets/491202/23125911/280ea098-f742-11e6-8eb0-a496a2f1f49c.png">
Also, the new plugin does not appear under Sketch plugins menu (tried restarting Sketch).

**Comment by mathieudutour** [comment]
I just fixed a bug when specifying the absolute path to the plugin instead of the relative path. Does it fix your issue?

**Comment by amin-nas** [comment]
Updated and created a new project. The symlink is pointing to the package.json file now:
/Users/aminnassiri/Projects/skpm_test_3/package.json

**Comment by mathieudutour** [comment]
Oh I'm tired sorry. Should work now. (no need to create a new project, just run the `link` command again)

**Comment by amin-nas** [comment]
Sweet! Working perfectly 🙌
