### ISSUE TITLE
`skpm link` should autodetect local plugin?

### ISSUE THREAD

**Issue by bomberstudios** [sketch-pm/skpm#17]
I spent a few minutes trying to find out the right path argument for `skpm link`. I think it would be nice if it autodetected that it's being run in a plugin development folder, and do the right thing automatically (i.e: make `skpm link` do a `skpm link .` under the hood if you run it on a project folder).

Apologies in advance if I'm not making myself very clear, coffee hasn't kicked in yet : )

**Comment by mathieudutour** [comment]
Oh yes good idea, I suppose it's the most common use case

**Comment by mathieudutour** [comment]
fix in https://github.com/sketch-pm/skpm/commit/d0388a6136d9411824d66ace2db9e7035c3d7337

**Comment by bomberstudios** [comment]
👏👏👏
