### ISSUE TITLE
Add `--watch` command info to README

### ISSUE THREAD

**Issue by AaronPresley** [sketch-pm/skpm#18]
Would be curious to hear your opinions on implementing a `watch` command. My initial thoughts for the workflow would be:

1. Within an initialized project, run the `skpm watch` command
2. `skpm` would then listen for all changes within the `src` (and `Resources`?) directory. Alternatively the user could set a `watch_glob` (or something similar) within the `package.json`?
3. When a change is detected, it would essentially run the `skpm build` and `skpm link` commands.
4. The changes would now be reflected within Sketch.

My main motivation for this request is to be able to make a change and have that change immediately reflected within Sketch. This seems like a much better workflow compared to running `skpm build` and `skpm link` manually after each change.

Do you have any thoughts or opinions on the above? Does this functionality already exist and I'm just missing it?

Thanks.

**Comment by mathieudutour** [comment]
you can already do `skpm build --watch`. The changes are directly reflected in sketch if you `skpm link` the plugin.

Was it what you were looking for?

**Comment by AaronPresley** [comment]
Ah, yes! I didn't see it in the docs and didn't look through the source.  That's exactly what I need. Thanks!

**Comment by mathieudutour** [comment]
Good point, do you want to make a PR to highlight the option?

**Comment by AaronPresley** [comment]
Certainly. Will try and get to it today or tomorrow.
