### ISSUE TITLE
Can't use Cocoa Braces Syntax

### ISSUE THREAD

**Issue by AaronPresley** [sketch-pm/skpm#22]
I have a section of my plugin where I need to use Cocoa. This is obviously invalid JS, so I'm receiving an error on build.

I have some more details on [this post](http://sketchplugins.com/d/137-cocoascript-braces-to-dot-syntax) over at the Sketch Plugins forum, but I'm curious how you use Cocoa within your plugins?

Would appreciate guidance on either how to get Cocoa to compile, or how to properly convert to dot notation.

**Comment by mathieudutour** [comment]
you never NEED to use cocoascript. Cocoascript breaks every tooling available in javascript.

In your example, you can use `NSXMLNode.attributeWithName_stringValue("attr", "val")`

**Comment by mathieudutour** [comment]
sometime there is trailing underscore for some reasons `NSXMLNode.attributeWithName_stringValue_("attr", "val")`

**Comment by AaronPresley** [comment]
Oh my god I could kiss you. Thanks so much.

Is there anywhere that has this syntax conversion is documented? I'm trying to teach myself to fish here but am finding the documentation hard to locate... I could also just be dense.

**Comment by mathieudutour** [comment]
hum probably but I can't find a link.
But it's quite straight forward: `[Class methodWithArg1: @'arg1' andArg2:@'arg2 andArg3:@'arg3]` -> `Class.methodWithArg1_andArg2_andArg3('arg1', 'arg2', 'arg3')`

**Comment by AaronPresley** [comment]
Ah so it is because I'm dense. Many thanks.

**Comment by joekim** [comment]
@AaronPresley @mathieudutour Hunted down a reference for you all on the syntax conversion.

http://www.mugginsoft.com/kosmictask/help/languages/javascript-cocoa

`JSCocoa supports two ways to call methods on Cocoa classes and objects. The first uses JavaScript property syntax. Cocoa method signatures are converted to function names by replacing : (colon) with _ (underscore). The trailing underscore on function names may be omitted.`

Cross posted on sketchplugin.com forum.
