### ISSUE TITLE
Getting error "Can't find variable: exports" in WebUI after updating to 0.7.2

### ISSUE THREAD

**Issue by AaronPresley** [sketch-pm/skpm#25]
After updating to the latest version, I'm getting the following JS console error when opening up a WebUI view:

```
ReferenceError: Can't find variable: exports
```

I've gone through a few of the previous commits, and the last commit that successfully compiles is `be946f4f656cb83c9e6387978b1ca40670d292af`.

Should I change how my Resource files are getting compiled? Would appreciate some direction on this so I can use the latest code.

**Comment by mathieudutour** [comment]
Should be fixed with 0.7.3. Can you confirm?

**Comment by AaronPresley** [comment]
It seems that's done the trick after reinstalling all `npm` dependencies.

Many thanks!
