### ISSUE TITLE
Can't use `require` method for importing modules

### ISSUE THREAD

**Issue by AaronPresley** [sketch-pm/skpm#26]
This is likely an issue with my own babel setup, but when using an external npm module (in this case [xml2js](#)), I'm getting the following error:

```
<Error>: ReferenceError: Can't find variable: require.
	Plugin “[Plugin Name]”, line 47:
	» var Util = _interopDefault(require('util'));
2017-04-06 15:57:02.173 Sketch[15619:8424183] Exception: {
    column = 35;
    line = 47;
}
```

This same error happens any time I use a module that uses the `require` method of importing modules. Here's my `.babelrc`:

```
{
  presets: [
    ["es2015", {modules: false}],
    "react",
  ],
  plugins: [
    "external-helpers",
    "transform-react-jsx",
  ],
}
```

I imagine I'm missing something obvious here... the `es2015` preset should do the conversion, shouldn't it?

Thanks.

**Comment by mathieudutour** [comment]
util is a native node module. It can't be bundle. There should be a warning when you build your plugin saying something like "can't find package util, treating it as an external dependency".

**Comment by AaronPresley** [comment]
Bad example perhaps, but even having something like `require('./local-module')` gives the same error.

I don't often use that method of importing, but some third party modules seem to (whether or not it's referencing an external dependency).

Is it a babel config I'm missing?

**Comment by mathieudutour** [comment]
i don't think it's a babel config, rollup is supposed to handle require. 
But we used skpm a lot with react-sketchapp which uses require. 
I don't have my laptop this weekend but if you can create a small repro in a repo, I can have a look next week

**Comment by AaronPresley** [comment]
I've created an [example repo here](https://github.com/AaronPresley/require-example).

You'll notice you can run `skpm build` and it successfully builds, but if you try to run the plugin from within Sketch you get the following error:

```
Apr  7 12:59:12  my-command (Sketch Plugin)[34375] <Error>: ReferenceError: Can't find variable: require.
	Plugin “my-command”, line 45:
	» const someModule = require('./some-module');
2017-04-07 12:59:12.920 Sketch[34375:9747056] Exception: {
    column = 27;
    line = 45;
}
```

Currently on Sketch 42, skpm v0.7.3

Would appreciate any help you can provide next week. I'll tinker with it a bit and let you know if I figure anything out.

**Comment by mathieudutour** [comment]
Oh I understand now. So yes, it looks like it's not possible to require a local plugin: https://github.com/rollup/rollup/issues/316

**Comment by AaronPresley** [comment]
Hmm, okay. I guess if I ever _need_ to use `require()` I'll just use some of the libs they mention.

Thanks!

**Comment by mathieudutour** [comment]
you should be able to use require now, we switched from rollup to webpack

**Comment by AaronPresley** [comment]
👏  Woo-hoo! 👏 

I feel this is a fantastic move considering how widely used webpack is (and selfishly it's what I personally use).

Thanks so much! This is great.

**Comment by mathieudutour** [comment]
indeed. I used rollup at the beginning because I already use webpack so wanted to learned rollup ;)
